site_name: PYTHON Group Project Docs


nav:
    - Welcome to PYTHON Group Project: index.md
    
    - Features:
        - Development:
            - CI/CD pipeline: pipeline.md
        - Core Services:
            - Application Programing Interface: api.md
            - Great Prediction: prediction.md
        - User Interfaces:
            - Interactive Streamlit Dashboard: Streamlit.md
            - Reactive Marimo Notebook: marimo_notebook.md
    


theme:
  name: material
  palette:
    primary: brown
    accent: blue
  features:
    - search.suggest
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.